[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake"
]

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "python -m pytest {package}/tests"
skip = ["*-win32"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]