[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake"
]

[tool.cibuildwheel]
before-test = "python -m pip install pytest"
test-command = "python -m pytest {package}/tests"
skip = ["cp36-*", "pp*"]


[tool.pytest.ini_options]
testpaths = [
    "tests",
]