name: Get-PR-Label
on:
  workflow_call:
    outputs:
      PRLabel: 
        value: ${{ jobs.Get-PR-Label.outputs.PR-label }}

permissions: write-all

jobs:
  Get-PR-Label:
    name: Get-PR-Label
    runs-on: ubuntu-latest
    outputs:
      PR-label: ${{ steps.GetCurrentPRLabel.outputs.match }}
    steps:
      - uses: actions/checkout@v2
      - id: GetCurrentPRLabel
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major, minor, patch

      - name: Failure
        if: failure()
        run: |
          echo "Invalid pull request labels, make sure to set one and only one of the following labels on the pull request: major, minor, patch" >> $GITHUB_STEP_SUMMARY

      - name: Success
        run: |
          echo "PR label checks passed successfully ✔" >> $GITHUB_STEP_SUMMARY
