name: Run-Ctests
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run unit tests
      uses: HorstBaerbel/action-ctest@1.1
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: '--config Release'
        ctestoptions: ''